using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace R8.RedisHashMap
{
    public partial class SourceGenerator
    {
        /// <summary>
        /// Generates the main context source file containing the Default instance and lazy-initialized helper properties.
        /// </summary>
        private static void GenerateContextSource(SourceProductionContext ctx, ContextOptions contextOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {contextOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Runtime.CompilerServices;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {contextOptions.AccessibilityModifier} partial {contextOptions.Keyword} {contextOptions.DisplayName}
    {{
        public static readonly {contextOptions.ObjectTypeSymbol} Default = new {contextOptions.ObjectTypeSymbol}();

        {string.Join(@"
        ", contextOptions.Types.Select(typeOptions => $"private readonly {typeOptions.HelperTypeName} _{typeOptions.DisplayName.ToCamelCase()} = new {typeOptions.HelperTypeName}();"))}

        {string.Join(@"
        ", contextOptions.Types.Select(typeOptions => $"{typeOptions.AccessibilityModifier} {typeOptions.HelperTypeName} {typeOptions.DisplayName} {{ [MethodImpl(MethodImplOptions.AggressiveInlining)] get {{ return _{typeOptions.DisplayName.ToCamelCase()}; }} }}"))}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the converters source file containing lazy-initialized converter instances.
        /// </summary>
        private static void GenerateConvertersSource(SourceProductionContext ctx, ContextOptions contextOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {contextOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Runtime.CompilerServices;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {contextOptions.AccessibilityModifier} partial {contextOptions.Keyword} {contextOptions.DisplayName}
    {{
        {string.Join(@"
        ", contextOptions.Converters.Select(c => $"private readonly Lazy<{c.ConverterType}> _{c.ConverterName.ToCamelCase()} = new Lazy<{c.ConverterType}>(() => new {c.ConverterType}());"))}

        {string.Join(@"
        ", contextOptions.Converters.Select(c => $"public {c.ConverterType} {c.ConverterName} => _{c.ConverterName.ToCamelCase()}.Value;"))}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.Converters.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the helper class source file containing serialization/deserialization methods.
        /// </summary>
        private static void GenerateHelperSource(SourceProductionContext ctx, ContextOptions contextOptions, ObjectOptions typeOptions)
        {
            var generationMode = typeOptions.GenerationMode ?? contextOptions.GenerationMode;
            var isDeserialization = generationMode is CacheGenerationMode.Default or CacheGenerationMode.Deserialization;
            var isSerialization = generationMode is CacheGenerationMode.Default or CacheGenerationMode.Serialization;
            // The cache also carries the writer options, so it is required by every JSON-writing helper,
            // including ones whose only JSON properties are JsonElement/JsonDocument.
            var anyJsonWrite = isSerialization && typeOptions.Properties.Exists(c => c.IsJsonWrite);
            var anyJsonRead = isDeserialization && typeOptions.Properties.Exists(c => c.RequiresJsonTypeInfo);
            var needsTypeInfoCache = anyJsonWrite || anyJsonRead;

            var sourceText = SourceText.From($@"// Original source: {typeOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Collections.Concurrent;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {typeOptions.AccessibilityModifier} partial class {typeOptions.HelperName}
    {{
        {(isDeserialization ? BuildFromHashEntries(contextOptions, typeOptions) : "")}
        {(isSerialization ? BuildGetHashEntries(contextOptions, typeOptions) : "")}

{(anyJsonWrite ? @"
        [ThreadStatic] private static global::R8.RedisHashMap.PooledBufferWriter? _pooledBufferWriter;
        [ThreadStatic] private static Utf8JsonWriter? _utf8JsonWriter;
        [ThreadStatic] private static object? _utf8JsonWriterKey;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static global::R8.RedisHashMap.PooledBufferWriter GetPooledBufferWriter()
        {
            var writer = _pooledBufferWriter;
            if (writer == null)
                return CreatePooledBufferWriter();

            writer.ResetWrittenCount();
            return writer;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static global::R8.RedisHashMap.PooledBufferWriter CreatePooledBufferWriter()
        {
            var writer = new global::R8.RedisHashMap.PooledBufferWriter(4096);
            _pooledBufferWriter = writer;
            return writer;
        }

        /// <summary>
        /// Returns a thread-local writer bound to <paramref name=""bufferWriter""/>. The writer carries the encoder and
        /// indentation settings, so it is rebuilt whenever the caller switches to a different options instance.
        /// </summary>
        private static Utf8JsonWriter GetUtf8JsonWriter(global::R8.RedisHashMap.PooledBufferWriter bufferWriter, __JsonTypeInfoCache cache)
        {
            var jsonWriter = _utf8JsonWriter;
            if (jsonWriter == null || !object.ReferenceEquals(_utf8JsonWriterKey, cache.Key))
            {
                jsonWriter = new Utf8JsonWriter(bufferWriter, cache.WriterOptions);
                _utf8JsonWriter = jsonWriter;
                _utf8JsonWriterKey = cache.Key;
                return jsonWriter;
            }

            jsonWriter.Reset(bufferWriter);
            return jsonWriter;
        }" : "")}
{(needsTypeInfoCache ? BuildTypeInfoCache(typeOptions) : "")}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.{typeOptions.DisplayName}.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the property names source file containing field constants and RedisValue fields.
        /// </summary>
        private static void GeneratePropertyNamesSource(SourceProductionContext ctx, ContextOptions contextOptions, ObjectOptions typeOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {typeOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {typeOptions.AccessibilityModifier} partial class {typeOptions.HelperName}
    {{
        {BuildPropertyFields(contextOptions, typeOptions)}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.{typeOptions.DisplayName}.PropertyNames.g.cs";

            ctx.AddSource(fileName, sourceText);
        }
    }
}
