using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace R8.RedisHashMap
{
    public partial class SourceGenerator
    {
        /// <summary>
        /// Generates the main context source file containing the Default instance and lazy-initialized helper properties.
        /// </summary>
        private static void GenerateContextSource(SourceProductionContext ctx, ContextOptions contextOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {contextOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Runtime.CompilerServices;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {contextOptions.AccessibilityModifier} partial {contextOptions.Keyword} {contextOptions.DisplayName}
    {{
        public static readonly {contextOptions.ObjectTypeSymbol} Default = new {contextOptions.ObjectTypeSymbol}();

        {string.Join(@"
        ", contextOptions.Types.Select(typeOptions => $"private readonly Lazy<{typeOptions.HelperTypeName}> _{typeOptions.DisplayName.ToCamelCase()} = new Lazy<{typeOptions.HelperTypeName}>(() => new {typeOptions.HelperTypeName}());"))}

        {string.Join(@"
        ", contextOptions.Types.Select(typeOptions => $"{typeOptions.AccessibilityModifier} {typeOptions.HelperTypeName} {typeOptions.DisplayName} => _{typeOptions.DisplayName.ToCamelCase()}.Value;"))}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the converters source file containing lazy-initialized converter instances.
        /// </summary>
        private static void GenerateConvertersSource(SourceProductionContext ctx, ContextOptions contextOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {contextOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Runtime.CompilerServices;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {contextOptions.AccessibilityModifier} partial {contextOptions.Keyword} {contextOptions.DisplayName}
    {{
        {string.Join(@"
        ", contextOptions.Converters.Select(c => $"private readonly Lazy<{c.ConverterType}> _{c.ConverterName.ToCamelCase()} = new Lazy<{c.ConverterType}>(() => new {c.ConverterType}());"))}

        {string.Join(@"
        ", contextOptions.Converters.Select(c => $"public {c.ConverterType} {c.ConverterName} => _{c.ConverterName.ToCamelCase()}.Value;"))}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.Converters.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the helper class source file containing serialization/deserialization methods.
        /// </summary>
        private static void GenerateHelperSource(SourceProductionContext ctx, ContextOptions contextOptions, ObjectOptions typeOptions)
        {
            var generationMode = typeOptions.GenerationMode ?? contextOptions.GenerationMode;
            var isDeserialization = generationMode == CacheGenerationMode.Default || generationMode == CacheGenerationMode.Deserialization;
            var isSerialization = generationMode == CacheGenerationMode.Default || generationMode == CacheGenerationMode.Serialization;

            var sourceText = SourceText.From($@"// Original source: {typeOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using System.Buffers;
using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Runtime.CompilerServices;

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {typeOptions.AccessibilityModifier} partial class {typeOptions.HelperName}
    {{
        private static readonly ArrayPool<HashEntry> arrayPool = ArrayPool<HashEntry>.Create({typeOptions.Properties.Count}, 1_000);

        {(isDeserialization ? BuildFromHashEntries(contextOptions, typeOptions) : "")}
        {(isSerialization ? BuildGetHashEntries(contextOptions, typeOptions) : "")}

{(typeOptions.Properties.Any(c => c.HasUtf8JsonWriter) ? @$"
        [ThreadStatic] private static ArrayBufferWriter<byte>? _arrayBufferWriter;
        [ThreadStatic] private static Utf8JsonWriter? _utf8JsonWriter;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static ArrayBufferWriter<byte> GetArrayBufferWriter()
        {{
            var writer = _arrayBufferWriter;
            if (writer == null)
            {{
                writer = new ArrayBufferWriter<byte>();
                _arrayBufferWriter = writer;
            }}

            return writer;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static Utf8JsonWriter GetUtf8JsonWriter(ArrayBufferWriter<byte> bufferWriter)
        {{
            var jsonWriter = _utf8JsonWriter;
            if (jsonWriter == null)
            {{
                jsonWriter = new Utf8JsonWriter(bufferWriter, {nameof(PooledJsonSerializer)}.{nameof(PooledJsonSerializer.ReusableJsonWriterOptions)});
                _utf8JsonWriter = jsonWriter;
            }}
            else
            {{
                jsonWriter.Reset(bufferWriter);
            }}

            return jsonWriter;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlyMemory<byte> GetBytes<T>(ArrayBufferWriter<byte> arrayBufferWriter, Utf8JsonWriter utf8JsonWriter, T value, JsonSerializerOptions? serializerOptions = null)
        {{
            arrayBufferWriter.Clear();
            utf8JsonWriter.Reset(arrayBufferWriter);
            return {nameof(PooledJsonSerializer)}.{nameof(PooledJsonSerializer.GetBytes)}<T>(utf8JsonWriter!, arrayBufferWriter!, value, serializerOptions);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ReadOnlyMemory<byte> GetBytes<T>(ArrayBufferWriter<byte>? arrayBufferWriter, Utf8JsonWriter? utf8JsonWriter, T value, JsonSerializerContext serializerContext)
        {{
            arrayBufferWriter.Clear();
            utf8JsonWriter.Reset(arrayBufferWriter);
            return serializerContext.GetTypeInfo(typeof(T)) is JsonTypeInfo<T> jsonType
                ? {nameof(PooledJsonSerializer)}.{nameof(PooledJsonSerializer.GetBytes)}<T>(utf8JsonWriter!, arrayBufferWriter!, value, jsonType)
                : {nameof(PooledJsonSerializer)}.{nameof(PooledJsonSerializer.GetBytes)}<T>(utf8JsonWriter!, arrayBufferWriter!, value, serializerContext.Options);
        }}" : "")}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.{typeOptions.DisplayName}.g.cs";

            ctx.AddSource(fileName, sourceText);
        }

        /// <summary>
        /// Generates the property names source file containing field constants and RedisValue fields.
        /// </summary>
        private static void GeneratePropertyNamesSource(SourceProductionContext ctx, ContextOptions contextOptions, ObjectOptions typeOptions)
        {
            var sourceText = SourceText.From($@"// Original source: {typeOptions.ObjectTypeSymbol.Type}
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

using StackExchange.Redis;

namespace {contextOptions.Namespace}
{{
    {typeOptions.AccessibilityModifier} partial class {typeOptions.HelperName}
    {{
        {BuildPropertyFields(contextOptions, typeOptions)}
    }}
}}", Encoding.UTF8);

            var fileName = $"{contextOptions.DisplayName}.{typeOptions.DisplayName}.PropertyNames.g.cs";

            ctx.AddSource(fileName, sourceText);
        }
    }
}
